modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="enchantmentsplusplus"
version="1.0.0"
displayName="Enchantments++"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="SparkleArts"
description='''
Add more Enchantments into the game
'''

[[dependencies.enchantmentsplusplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




